name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build-frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Go to client folder
        run: cd client/amour-en-images

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version if needed

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        working-directory: client/amour-en-images

      - name: Build project
        run: npm run build
        working-directory: client/amour-en-images

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: client/amour-en-images/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: client/amour-en-images/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: client/amour-en-images/dist
